# services:
#   dcebox-frontend:
#     image: slada/dcef:main
#     restart: unless-stopped
#     volumes:
#       - ./dcejson_exports:/dcef/exports:ro,z
#       - dcef_cache:/dcef/cache
#     ports:
#       - 127.0.0.1:21011:21011
#
# volumes:
#   dcef_cache: